version: '3'
services:
  server:
    build: ./server
    command: go run *.go
    volumes:
      - ./server:/go/src/app
    ports:
      - '8080:3000'
  client:
    build: ./client
    command: npm start
    volumes:
      - ./client:/usr/src/app
    ports:
      - '9000:3000'
