version: '3'
services:
  server:
    build: ./server
    command: go run main.go
    tty: true
    volumes:
      - ./server:/go/src/app
    ports:
      - '8080:8080'
    working_dir: /go/src/app
  client:
    build: ./client
    command: npm start
    volumes:
      - ./client:/usr/src/app
    ports:
      - '4000:3000'
